service: srtask
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.randNum
    events:
     - httpApi:
         path: /users/create
         method: get